version: 0.2

phases:
  build:
    run: chmod +x ./gradlew
    commands:
      - echo Entered the build phase...
      - ./gradlew clean
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - build/libs/TeaTimeJar-0.0.1-SNAPSHOT.jar
  discard-paths: yes